"""Add powers column to heroes table

Revision ID: b859b4569542
Revises: 60f9ead7b42a
Create Date: 2025-09-20 15:17:19.944723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b859b4569542'
down_revision: Union[str, Sequence[str], None] = '60f9ead7b42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heros', sa.Column('powers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heros', 'powers')
    # ### end Alembic commands ###
